---
#
# Install a local kvm hypervisor and tools to run virt-lab.
#
# Usage:
#    ansible-galaxy install -r requirements.yaml
#    ansible-playbook kvm.yaml
#
- hosts: localhost
  vars:
    # Setup libvirt's dnsmasq with servers and the no-resolv to
    # avoid a DNS loop with systemd-resolved.
    pri_domain_name: example.com
    pri_dns: 8.8.8.8
    sec_dns: 8.8.4.4
    kvm_config_virtual_networks: true
    kvm_virtual_networks:
      - name: virtlab
        mode: nat
        bridge_name: vlbr0
        enable_dhcp: true
        dhcp_gateway: 192.168.123.1
        dhcp_netmask: 255.255.255.0
        dhcp_scope_start: 192.168.123.32
        dhcp_scope_end: 192.168.123.254
        autostart: true
        state: active
  roles:
    - role: mrlesmithjr.kvm

  tasks:
    - name: Set environment variable in profile.
      lineinfile:
        path: "{{ ansible_facts['user_dir'] }}/.profile"
        firstmatch: true
        regexp: '^LIBVIRT_DEFAULT_URI='
        line: "LIBVIRT_DEFAULT_URI='qemu:///system'"
      when: not 'LIBVIRT_DEFAULT_URI' in ansible_facts.env
      notify:
        - logout required

  handlers:
    - name: logout required
      pause:
        prompt: |
          Your profile has been updated.
          Please log out and log in again before continuing.
          You may use 'su - {{ ansible_user }}' to login.
          Press <enter> to continue.
